INSERT INTO Course(ID,NAME, CREATED_DATE, LAST_UPDATED_DATE) VALUES(10001, 'Jpa in 50 steps', SYSDATE(), SYSDATE());
INSERT INTO Course(ID,NAME, CREATED_DATE, LAST_UPDATED_DATE) VALUES(10002, 'Spring in 50 steps', SYSDATE(), SYSDATE());
INSERT INTO Course(ID,NAME, CREATED_DATE, LAST_UPDATED_DATE) VALUES(10003, 'Java in 50 steps', SYSDATE(), SYSDATE());